services:
  database:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=root  '
    ports:
      - '3307:3306'