services:
  database:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=bridee'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=bridee'
      - 'MYSQL_PASSWORD=bridee'
    ports:
      - '3307:3306'