spring:
  application:
    name:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/bridee}
    username: ${MYSQL_USERNAME:bridee}
    password: ${MYSQL_PASSWORD:bridee}

services:
  bridee:
    email:
      inviteUrl: ${BRIDEE_INVITE_URL:http://localhost:8080}
      host: ${BRIDEE_EMAIL_HOST:smtp.gmail.com}
      user: ${BRIDEE_EMAIL_USERNAME:""}
      password: ${BRIDEE_EMAIL_PASSWORD:""}