server:
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_updates: true
        jdbc:
          batch_size: 5
  application:
    name: bridee-api
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/bridee}
    username: ${MYSQL_USERNAME:bridee}
    password: ${MYSQL_PASSWORD:bridee}
  cloud:
    azure:
      storage:
        blob:
          container-name: ${AZURE_DATASTORAGE_CONTAINER_NAME:""}

services:
  bridee:
    function:
      storage-function:
        url: ${BRIDEE_STORAGE_FUNCTION_URL:http://localhost:7000}
        api-key: ${BRIDEE_STORAGE_FUNCTION_API-KEY:"DEFAULT"}
    email:
      host: ${BRIDEE_EMAIL_HOST:smtp.gmail.com}
      user: ${BRIDEE_EMAIL_USERNAME:""}
      password: ${BRIDEE_EMAIL_PASSWORD:""}
    whatsapp:
      inviteUrl: ${BRIDEE_INVITE_URL:http://localhost:8080}
      url: ${WHATSAPP_API_URL:https://app.whatsgw.com.br/api/WhatsGw}
      apiKey: ${WHATSAPP_API_KEY:6c28732c-85a2-4286-9d2e-41dc4658e31d}
      phoneSender: ${BRIDEE_PHONE_NUMBER:5573988110632}
    pexels:
      url: ${PEXELS_URL:https://api.pexels.com}
      apiKey: ${PEXELS_API_KEY:0SuVakENYYmZjAdLk2M3ltPqPPcgS8SHHgHakSYOqUQSVoCh9C1f2nQo}

jwt:
  secret:
    key: ${JWT_SECRET:fefwefefefewefwawefweafweawfwefawefawfwefwefawfwefawfwaefawfaw}

email:
  register:
    url: ${EMAIL_REGISTER_URL:http://localhost:8080/usuarios/ativar-conta}

registration:
  success:
    redirectUri: ${REGISTRATION_SUCCESS_REDIRECT_URI:http://localhost:5173/login}
  fail:
    redirectUri: ${REGISTRATION_FAIL_REDIRECT_URI:http://localhost:5173/reenviar-email}

azure:
  data-storage:
    container:
      url: ${AZURE_DATASTORAGE_CONTAINER_URL:""}
      sasToken: ${AZURE_DATASTORAGE_CONTAINER_TOKEN:""}
  blob-storage:
    connection-string: ${AZURE_DATASTORAGE_CONNECTION_STRING:""}

httpOnly:
  cookie:
    host: ${HTTPONLY_COOKIE_DOMAIN:localhost}

cache:
  manager:
    expireMinutes: ${CACHE_EXPIRE_MINUTES:20}