ALTER TABLE tarefa MODIFY COLUMN descricao VARCHAR(1200);
ALTER TABLE imagem ADD COLUMN extensao VARCHAR(45) NOT NULL;
ALTER TABLE imagem ADD COLUMN tipo VARCHAR(45) NOT NULL;
ALTER TABLE imagem ADD COLUMN data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP;