ALTER TABLE orcamento DROP CONSTRAINT fkCasalXAssessor;
ALTER TABLE orcamento DROP CONSTRAINT fkFornecedorOrcamento;
ALTER TABLE orcamento DROP CONSTRAINT fkItemOrcamento;
ALTER TABLE casal_assessor DROP CONSTRAINT fkAssessor;
ALTER TABLE casal_assessor DROP CONSTRAINT fkCasal;
DROP TABLE casal_assessor;
ALTER TABLE fornecedor_casal DROP CONSTRAINT fkFornecedor;
ALTER TABLE fornecedor_casal DROP CONSTRAINT fkUsuarioFornecedorCasal;
DROP TABLE fornecedor_casal;
ALTER TABLE casal ADD COLUMN assessor_id INT;
ALTER TABLE casal ADD CONSTRAINT fkAssessorCasal FOREIGN KEY (assessor_id) REFERENCES assessor(id);
ALTER TABLE casal ADD COLUMN orcamento_total DECIMAL(5,2);
DROP TABLE orcamento;
ALTER TABLE item_orcamento ADD COLUMN casal_id INT;
ALTER TABLE item_orcamento ADD CONSTRAINT itemCasalOrcamento FOREIGN KEY (casal_id) REFERENCES casal(id);
ALTER TABLE convite RENAME COLUMN evento_id TO casamento_id;
ALTER TABLE mesa RENAME COLUMN evento_id TO casamento_id;
ALTER TABLE convite DROP CONSTRAINT fkConviteAcompanhante;
ALTER TABLE convite DROP COLUMN acompanhante_id;
ALTER TABLE convite DROP CONSTRAINT fkConvidadoEvento;
ALTER TABLE convite DROP COLUMN convidado_id;
ALTER TABLE convite ADD COLUMN nome VARCHAR(70);
ALTER TABLE convite ADD COLUMN pin CHAR(6);
ALTER TABLE convidado DROP COLUMN pin;
ALTER TABLE convidado ADD COLUMN tipo VARCHAR(45);
ALTER TABLE convidado ADD COLUMN convite_id INT;
ALTER TABLE convidado ADD CONSTRAINT convidadoConvite FOREIGN KEY (convite_id) REFERENCES convite(id);
ALTER TABLE acompanhante DROP CONSTRAINT fkConvidado;
DROP TABLE acompanhante;
ALTER TABLE cronograma RENAME COLUMN evento_id TO casamento_id;
