name: Build and deploy JAR app to Azure Web App - bridee-api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generating tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{secrets.AWS_ACCESS_KEY}}"
          aws-secret-access-key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          aws-session-token: "${{secrets.AWS_SESSION_TOKEN}}"
          aws-region: "${{secrets.AWS_REGION}}"

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        id: docker-image
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          TAG: ${{steps.generate_tag.outputs.sha}}
        run: |
          docker build -t $REGISTRY/bridee-api:$TAG .
          docker tag $REGISTRY/bridee-api:$TAG $REGISTRY/bridee-api:latest
          docker push --all-tags $REGISTRY/bridee-api
          IMAGE=$(echo $REGISTRY/bridee-api:$TAG)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT