name: Bridee CI pipeline
on:
  push:
    branches:
     - ci/cd
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn clean package

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: petclinic-war
          path: "/petclinic.war"
          if-no-files-found: error